openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http'
paths:
  /cake:
    get:
      description: Получить список всех тортов
      responses:
        200:
          description: успешное выполнение сервера
          content:
            aplication/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/cakes'


components:
  schemas:
    cakes:
      additionalProperties: false
      type: object
      properties:
        cake_list:
          type: array
          items:
             $ref: '#/components/schemas/cake'


    cake:
      type: object
      description: Краткие данные о торте
      required:
        - id
        - name
        - calories
        - image
        - price
        - weight
      properties:
        id:
          type:number
          description: идентификатор торта
        name:
         type: string
         description: название торта
        calories:
          type: number
          description: число калорий
        image:
          type: string
          description: относительный url картинки торта
        price:
          type: number
          description: цена торта
        weight:
          type: number
          description: вес торта








